GET http://localhost:3000/users/6189a3ec3f8b34ed58e5829c

###

GET http://localhost:3000/users

###

DELETE http://localhost:3000/users/6189a3ec3f8b34ed58e5829c


###

PATCH  http://localhost:3000/users/61911d8ca8402a5be0182808
Content-Type: application/json

{
    
    "address" : {
        "street" : "La goulette",
        "city" : "Tunis" ,
        "State" : "Tunis",
        "postalCode" : 2060 ,
        "country" : "Tunis"
    }
}